[package]
name = "AstromechAPI"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
embedded-hal = "0.2"
pwm-pca9685 = "1.0.0"
rppal = "0.19.0"

[build]
target = "armv7-unknown-linux-gnueabihf" # Adjust as needed
