name: Customize Commit Timestamps

on: [push]

jobs:
  customize-timestamps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set commit timestamps for new commits
        run: |
          git filter-branch --env-filter '
            if test -z "$GIT_COMMIT"; then
              export GIT_COMMITTER_DATE="$(date -u +"%Y-%m-%dT17:30:00+00:00")"
            fi
          ' HEAD
          git push --force-with-lease
